const allProjects = [
  {
    name: 'KGK AAROHAN',
    address: '4, Sardar Patel Marg',
    locality: 'C Scheme',
    city: 'Jaipur',
    units: '5 & 4 bhk',
    image: proj1,
    logo: projLogo1,
    type: 'Residential',
  },
  {
    name: 'KGK AKSHAR',
    address: 'Vande Mataram Road',
    locality: 'Mansarovar',
    city: 'Jaipur',
    units: '4 & 3 bhk',
    image: proj2,
    logo: projLogo2,
    type: 'Residential',
  },
  {
    name: 'KGK AMULYA',
    address: 'Near 7 Number Stand, Airport Road',
    locality: 'Jagatpura',
    city: 'Jaipur',
    units: '3 & 2 bhk',
    image: proj3,
    logo: projLogo3,
    type: 'Residential',
  },
  {
    name: 'KGK AAROHAN',
    address: 'Near Jaipur International Airport',
    locality: '',
    city: 'Jaipur',
    units: 'Commercial SPACE',
    image: proj4,
    logo: projLogo4,
    type: 'Commercial',
  },
  {
    name: 'KGK AKSHAR',
    address: 'Jaipur-Ajmer Highway',
    locality: 'Near Bagru',
    city: 'Jaipur',
    units: 'Commercial SPACE',
    image: proj5,
    logo: projLogo5,
    type: 'Commercial',
  },
  {
    name: 'RSM NIYATI',
    address: null,
    locality: null,
    city: null,
    units: null,
    image: proj6,
    logo: null,
    type: 'Mumbai',
  },
  {
    name: 'RSM DIAMOND',
    address: null,
    locality: null,
    city: null,
    units: null,
    image: proj7,
    logo: null,
    type: 'Mumbai',
  },
];